#!/bin/sh

iscsiadm -m iface -I iface0 --op=new
iscsiadm -m iface -I iface0 --op=update -n iface.hwaddress -v 00:1e:68:78:fb:47
iscsiadm -m iface -I iface1 --op=new
iscsiadm -m iface -I iface1 --op=update -n iface.hwaddress -v 00:1e:68:78:fb:48
