
node basenode {
	include hosts
	include ntp
	include snmp
	include sudo
}

node red-worker inherits basenode {
	include condor
#	include hadoop
	include fetch-crl
}

##############################################################################


node 'node001' inherits red-worker { }
node 'node002' inherits red-worker { }
node 'node003' inherits red-worker { }
node 'node004' inherits red-worker { }
node 'node005' inherits red-worker { }
node 'node006' inherits red-worker { }
node 'node007' inherits red-worker { }
node 'node008' inherits red-worker { }
node 'node009' inherits red-worker { }
node 'node010' inherits red-worker { }
node 'node011' inherits red-worker { }
node 'node012' inherits red-worker { }
node 'node013' inherits red-worker { }
node 'node014' inherits red-worker { }
node 'node015' inherits red-worker { }
node 'node016' inherits red-worker { }
node 'node017' inherits red-worker { }
node 'node018' inherits red-worker { }
node 'node019' inherits red-worker { }
node 'node020' inherits red-worker { }
node 'node021' inherits red-worker { }
node 'node022' inherits red-worker { }
node 'node023' inherits red-worker { }
node 'node024' inherits red-worker { }
node 'node025' inherits red-worker { }
node 'node026' inherits red-worker { }
node 'node027' inherits red-worker { }
node 'node028' inherits red-worker { }
node 'node029' inherits red-worker { }
node 'node030' inherits red-worker { }
node 'node031' inherits red-worker { }
node 'node032' inherits red-worker { }
node 'node033' inherits red-worker { }
node 'node034' inherits red-worker { }
node 'node035' inherits red-worker { }
node 'node036' inherits red-worker { }
node 'node037' inherits red-worker { }
node 'node038' inherits red-worker { }
node 'node039' inherits red-worker { }
node 'node040' inherits red-worker { }
node 'node041' inherits red-worker { }
node 'node042' inherits red-worker { }
node 'node043' inherits red-worker { }
node 'node044' inherits red-worker { }
node 'node045' inherits red-worker { }
node 'node046' inherits red-worker { }
node 'node047' inherits red-worker { }
node 'node048' inherits red-worker { }
node 'node049' inherits red-worker { }
node 'node050' inherits red-worker { }
node 'node051' inherits red-worker { }
node 'node052' inherits red-worker { }
node 'node053' inherits red-worker { }
node 'node054' inherits red-worker { }
node 'node055' inherits red-worker { }
node 'node056' inherits red-worker { }
node 'node057' inherits red-worker { }
node 'node058' inherits red-worker { }
node 'node059' inherits red-worker { }
node 'node060' inherits red-worker { }
node 'node061' inherits red-worker { }
node 'node062' inherits red-worker { }
node 'node063' inherits red-worker { }
node 'node064' inherits red-worker { }
node 'node065' inherits red-worker { }
node 'node066' inherits red-worker { }
node 'node067' inherits red-worker { }
node 'node068' inherits red-worker { }
node 'node069' inherits red-worker { }
node 'node070' inherits red-worker { }
node 'node071' inherits red-worker { }
node 'node072' inherits red-worker { }
node 'node073' inherits red-worker { }
node 'node074' inherits red-worker { }
node 'node075' inherits red-worker { }
node 'node076' inherits red-worker { }
node 'node077' inherits red-worker { }
node 'node078' inherits red-worker { }
node 'node079' inherits red-worker { }
node 'node080' inherits red-worker { }
node 'node081' inherits red-worker { }
node 'node082' inherits red-worker { }
node 'node083' inherits red-worker { }
node 'node084' inherits red-worker { }
node 'node085' inherits red-worker { }
node 'node086' inherits red-worker { }
node 'node087' inherits red-worker { }
node 'node088' inherits red-worker { }
node 'node089' inherits red-worker { }
node 'node090' inherits red-worker { }
node 'node091' inherits red-worker { }
node 'node092' inherits red-worker { }
node 'node093' inherits red-worker { }
node 'node094' inherits red-worker { }
node 'node095' inherits red-worker { }
node 'node096' inherits red-worker { }
node 'node097' inherits red-worker { }
node 'node098' inherits red-worker { }
node 'node099' inherits red-worker { }
node 'node100' inherits red-worker { }
node 'node101' inherits red-worker { }
node 'node102' inherits red-worker { }
node 'node103' inherits red-worker { }
node 'node104' inherits red-worker { }
node 'node105' inherits red-worker { }
node 'node106' inherits red-worker { }
node 'node107' inherits red-worker { }
node 'node108' inherits red-worker { }
node 'node109' inherits red-worker { }
node 'node110' inherits red-worker { }
node 'node111' inherits red-worker { }
node 'node112' inherits red-worker { }
node 'node113' inherits red-worker { }
node 'node114' inherits red-worker { }
node 'node115' inherits red-worker { }
node 'node116' inherits red-worker { }
node 'node117' inherits red-worker { }
node 'node118' inherits red-worker { }
node 'node119' inherits red-worker { }
node 'node120' inherits red-worker { }
node 'node121' inherits red-worker { }
node 'node122' inherits red-worker { }
node 'node123' inherits red-worker { }
node 'node124' inherits red-worker { }
node 'node125' inherits red-worker { }
node 'node126' inherits red-worker { }
node 'node127' inherits red-worker { }
node 'node128' inherits red-worker { }
node 'node129' inherits red-worker { }
node 'node130' inherits red-worker { }
node 'node131' inherits red-worker { }
node 'node132' inherits red-worker { }
node 'node133' inherits red-worker { }
node 'node134' inherits red-worker { }
node 'node135' inherits red-worker { }
node 'node136' inherits red-worker { }
node 'node137' inherits red-worker { }
node 'node138' inherits red-worker { }
node 'node139' inherits red-worker { }
node 'node140' inherits red-worker { }
node 'node141' inherits red-worker { }
node 'node142' inherits red-worker { }
node 'node143' inherits red-worker { }
node 'node144' inherits red-worker { }
node 'node145' inherits red-worker { }
node 'node146' inherits red-worker { }
node 'node147' inherits red-worker { }
node 'node148' inherits red-worker { }
node 'node149' inherits red-worker { }
node 'node150' inherits red-worker { }
node 'node151' inherits red-worker { }
node 'node152' inherits red-worker { }
node 'node153' inherits red-worker { }
node 'node154' inherits red-worker { }
node 'node155' inherits red-worker { }
node 'node156' inherits red-worker { }
node 'node157' inherits red-worker { }
node 'node158' inherits red-worker { }
node 'node159' inherits red-worker { }
node 'node160' inherits red-worker { }
node 'node161' inherits red-worker { }
node 'node162' inherits red-worker { }
node 'node163' inherits red-worker { }
node 'node164' inherits red-worker { }
node 'node165' inherits red-worker { }
node 'node166' inherits red-worker { }
node 'node167' inherits red-worker { }
node 'node168' inherits red-worker { }
node 'node169' inherits red-worker { }
node 'node170' inherits red-worker { }
node 'node171' inherits red-worker { }
node 'node172' inherits red-worker { }
node 'node173' inherits red-worker { }
node 'node174' inherits red-worker { }
node 'node175' inherits red-worker { }
node 'node176' inherits red-worker { }
node 'node177' inherits red-worker { }
node 'node178' inherits red-worker { }
node 'node179' inherits red-worker { }
node 'node180' inherits red-worker { }
node 'node181' inherits red-worker { }
node 'node182' inherits red-worker { }
node 'node183' inherits red-worker { }
node 'node184' inherits red-worker { }
node 'node185' inherits red-worker { }
node 'node186' inherits red-worker { }
node 'node187' inherits red-worker { }
node 'node188' inherits red-worker { }
node 'node189' inherits red-worker { }
node 'node190' inherits red-worker { }
node 'node191' inherits red-worker { }
node 'node192' inherits red-worker { }
node 'node193' inherits red-worker { }
node 'node194' inherits red-worker { }
node 'node195' inherits red-worker { }
node 'node196' inherits red-worker { }
node 'node197' inherits red-worker { }
node 'node198' inherits red-worker { }
node 'node199' inherits red-worker { }
node 'node200' inherits red-worker { }
node 'node201' inherits red-worker { }
node 'node202' inherits red-worker { }
node 'node203' inherits red-worker { }
node 'node204' inherits red-worker { }
node 'node205' inherits red-worker { }
node 'node206' inherits red-worker { }
node 'node207' inherits red-worker { }
node 'node208' inherits red-worker { }
node 'node209' inherits red-worker { }
node 'node210' inherits red-worker { }
node 'node211' inherits red-worker { }
node 'node212' inherits red-worker { }
node 'node213' inherits red-worker { }
node 'node214' inherits red-worker { }
node 'node215' inherits red-worker { }
node 'node216' inherits red-worker { }
node 'node217' inherits red-worker { }
node 'node218' inherits red-worker { }
node 'node219' inherits red-worker { }
node 'node220' inherits red-worker { }
node 'node221' inherits red-worker { }
node 'node222' inherits red-worker { }
node 'node223' inherits red-worker { }
node 'node224' inherits red-worker { }
node 'node225' inherits red-worker { }
node 'node226' inherits red-worker { }
node 'node227' inherits red-worker { }
node 'node228' inherits red-worker { }
node 'node229' inherits red-worker { }
node 'node230' inherits red-worker { }
node 'node231' inherits red-worker { }
node 'node232' inherits red-worker { }
node 'node233' inherits red-worker { }
node 'node234' inherits red-worker { }
node 'node235' inherits red-worker { }
node 'node236' inherits red-worker { }
node 'node237' inherits red-worker { }
node 'node238' inherits red-worker { }
node 'node239' inherits red-worker { }
node 'node240' inherits red-worker { }
node 'node241' inherits red-worker { }
node 'node242' inherits red-worker { }
node 'node243' inherits red-worker { }
node 'node244' inherits red-worker { }
node 'node245' inherits red-worker { }
node 'node246' inherits red-worker { }
node 'node247' inherits red-worker { }
node 'node248' inherits red-worker { }
node 'node249' inherits red-worker { }
node 'node250' inherits red-worker { }
node 'node251' inherits red-worker { }
node 'node252' inherits red-worker { }
node 'node253' inherits red-worker { }
node 'node254' inherits red-worker { }
node 'red-d8n1' inherits red-worker { }
node 'red-d8n2' inherits red-worker { }
node 'red-d8n3' inherits red-worker { }
node 'red-d8n4' inherits red-worker { }
node 'red-d8n5' inherits red-worker { }
node 'red-d8n6' inherits red-worker { }
node 'red-d8n7' inherits red-worker { }
node 'red-d8n8' inherits red-worker { }
node 'red-d8n9' inherits red-worker { }
node 'red-d8n10' inherits red-worker { }
node 'red-d8n11' inherits red-worker { }
node 'red-d8n12' inherits red-worker { }
node 'red-d8n13' inherits red-worker { }
node 'red-d8n14' inherits red-worker { }
node 'red-d8n15' inherits red-worker { }
node 'red-d8n16' inherits red-worker { }
node 'red-d8n17' inherits red-worker { }
node 'red-d8n18' inherits red-worker { }
node 'red-d8n19' inherits red-worker { }
node 'red-d8n20' inherits red-worker { }
node 'red-d9n1' inherits red-worker { }
node 'red-d9n2' inherits red-worker { }
node 'red-d9n3' inherits red-worker { }
node 'red-d9n4' inherits red-worker { }
node 'red-d9n5' inherits red-worker { }
node 'red-d9n6' inherits red-worker { }
node 'red-d9n7' inherits red-worker { }
node 'red-d9n8' inherits red-worker { }
node 'red-d9n9' inherits red-worker { }
node 'red-d9n10' inherits red-worker { }
node 'red-d9n11' inherits red-worker { }
node 'red-d9n12' inherits red-worker { }
node 'red-d9n13' inherits red-worker { }
node 'red-d9n14' inherits red-worker { }
node 'red-d9n15' inherits red-worker { }
node 'red-d9n16' inherits red-worker { }
node 'red-d9n17' inherits red-worker { }
node 'red-d9n18' inherits red-worker { }
node 'red-d9n19' inherits red-worker { }
node 'red-d9n20' inherits red-worker { }
